/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's tasks (single page; pagination deferred). */
        get: operations["listTasks"];
        put?: never;
        /** Create a task. */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's projects (single page; pagination deferred). */
        get: operations["listProjects"];
        put?: never;
        /** Create a project. */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered skills the caller can use as hints (single page). */
        get: operations["listSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one skill, including its instructions body. */
        get: operations["getSkill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one task. */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a task's first turn. */
        post: operations["startTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a follow-up user message into a running task. */
        post: operations["sendTaskMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent event stream of a task's runtime events.
         * @description SSE stream (text/event-stream). Each event's `data` is a JSON StreamEvent (block-oriented tagged union, discriminator `type`; see components.schemas.StreamEvent).
         *     Block-oriented stream model (0.3.0): the stream follows the Anthropic message-turn lifecycle — `message_start` opens a message shell, one or more `content_block_start` / `content_block_delta` / `content_block_stop` triplets carry incremental block content (text, thinking, tool_use, image), `message_delta` supplies the final stop_reason and cumulative usage, and `message_stop` closes the turn. Praxis-owned control events (`turn_paused`, `turn_resumed`, `skill_activation_requested`, `stream_end`, `ping`) are interleaved as they occur.
         *     ContentBlock uses adjacent tagging: `{"type":"<variant>","data":{...}}`. BlockDelta uses internal tagging: `{"type":"<variant>",...fields...}`.
         *     Stream semantics (v0.1.0, stable): 1. This is a READ-ONLY window onto the server-side session driver. Closing the
         *        stream (tab close, network drop) does NOT stop or affect task execution —
         *        the driver runs server-side, maintained by the session lease and recovered
         *        by the eager-recovery sweeper, and can progress with no inbound request.
         *     2. Closing the stream is NOT a cancel. Termination is only POST /v1/tasks/{id}/cancel. 3. The stream is LIVE-ONLY: it delivers events from the moment of subscription.
         *        There is no event id, no Last-Event-ID, and no replay; events emitted while a
         *        client is disconnected are not redelivered. The reconnect/catch-up story
         *        is GET /v1/tasks/{id}/history (render history, then re-subscribe).
         *     4. The stream always TERMINATES (0.1.4): the server emits a final
         *        `stream_end{task_status}` frame and closes the connection. It is sent
         *        immediately when subscribing to a task already in a terminal status
         *        (without reviving its session), after message_stop or a task failure,
         *        or on server-side session teardown (complete, cancel, lease loss).
         *        A client may treat `stream_end` as authoritative end-of-stream; reconnect
         *        only if `task_status` is non-terminal. Comment-line keep-alive frames
         *        are sent on idle streams.
         *
         *     On subscribe, the server re-emits any currently-pending ask_user content blocks (ToolUse blocks with tool_name `message_ask_user`) ahead of the live stream, so a reconnecting client recovers the `call_id` (ask_id). Clients MUST dedup by `call_id` (= `ask_id` in AnswerRequest).
         *     The event union is marked beta (x-praxis-stability): variant fields may change while cogito is pre-1.0; the set of variants only grows (consumers MUST ignore unknown `type`).
         */
        get: operations["taskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of a task's historical conversation events (chronological).
         * @description Returns a page of persisted Message objects for a task, paginated by a seq cursor. This is the catch-up half of the reconnect story: a client renders history here (see MessagePage / Message / ContentBlock), then subscribes to GET /v1/tasks/{id}/events for the live stream. History carries complete Message objects (all ContentBlock variants, stop_reason, usage, attachments); the live stream carries block-lifecycle deltas (BlockDelta) and turn-boundary events. The two do not overlap. A task with no session yet (draft) returns an empty page.
         *     Items within a page are ordered ascending (oldest first), so a client renders a page top-to-bottom directly. Pages walk newest -> older across calls: the first call (no cursor) returns the newest page so a freshly-opened task shows its latest state immediately; pass the returned next_before_seq as the `cursor` query parameter to fetch the next (older) page and PREPEND it as the user scrolls up. Following next_before_seq until it is absent walks the entire session into view. A whole turn is never split across a page boundary, and no message is repeated or skipped between pages.
         */
        get: operations["taskHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a non-terminal task. */
        post: operations["cancelTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a paused task complete. */
        post: operations["completeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer a pending message_ask_user question.
         * @description Submits an answer for a paused message_ask_user question. `ask_id` in AnswerRequest is the `call_id` of the `ToolUse` ContentBlock with `tool_name == "message_ask_user"` that initiated the pause. The `call_id` is delivered over the live event stream (in a `content_block_start` event) and re-emitted on subscribe so a reconnecting client can recover it. Clients MUST NOT hardcode ask_ids; always source them from the live stream or history.
         */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Kind of citation source. Open set; consumers tolerate unknown values.
         * @enum {string}
         */
        CitationSourceKind: "knowledge" | "web" | "file";
        /** @description Source attribution for a span within a Text content block. */
        Citation: {
            source_kind: components["schemas"]["CitationSourceKind"];
            /** @description Human-facing title of the cited source. */
            title?: string;
            /** @description Source URL. */
            url?: string;
            /** @description Source document id (knowledge base or file reference). */
            document_id?: string;
            /** @description The exact text excerpted from the source. */
            cited_text?: string;
            /** @description Inclusive start char offset into the citing Text block's text. */
            text_start?: number;
            /** @description Exclusive end char offset into the citing Text block's text. */
            text_end?: number;
        };
        /**
         * @description Provenance kind of a tool. Open set; consumers tolerate unknown values.
         * @enum {string}
         */
        SourceKind: "builtin" | "mcp" | "plugin" | "skill";
        /** @description Provenance of a tool invocation. */
        Source: {
            kind: components["schemas"]["SourceKind"];
            /** @description Provider name (e.g. MCP server id, plugin id). Absent for builtin. */
            name?: string;
        };
        /** @description Human-facing display metadata for a tool call. All fields are optional. */
        Display: {
            /** @description Short title to show instead of the raw tool name. */
            title?: string;
            /** @description Icon hint. */
            icon?: string;
            /** @description One-line human summary of the call. */
            summary?: string;
        };
        /**
         * @description Image source discriminant. Open set; consumers tolerate unknown values.
         * @enum {string}
         */
        ImageSourceKind: "base64" | "url" | "file_ref";
        /** @description Image bytes source (reserved; spec D5 — not yet populated). */
        ImageSource: {
            kind: components["schemas"]["ImageSourceKind"];
            /** @description MIME type, e.g. image/png. */
            media_type: string;
            /** @description Base64-encoded image bytes. Present when kind == base64. */
            data?: string;
            /** @description External image URL. Present when kind == url. */
            url?: string;
            /** @description Workspace file reference. Present when kind == file_ref. */
            file_id?: string;
        };
        /** @description One unit of message content. Adjacently tagged: {"type":"<variant>","data":{...}}. The set of variants only grows; consumers MUST ignore unknown type values. */
        ContentBlock: {
            /** @constant */
            type: "text";
            data: {
                /** @description The text content. */
                text: string;
                /** @description Source citations referencing spans of the text field. Omitted when empty. */
                citations?: components["schemas"]["Citation"][];
            };
        } | {
            /** @constant */
            type: "thinking";
            data: {
                /** @description Reasoning text; empty when redacted. */
                text: string;
                /** @description True when the provider redacted or encrypted the reasoning. Omitted when false. */
                redacted?: boolean;
            };
        } | {
            /** @constant */
            type: "tool_use";
            data: {
                /** @description Opaque tool-call id; correlates with the matching ToolResult. */
                call_id: string;
                /** @description Tool name. */
                tool_name: string;
                /** @description Tool arguments as a JSON object. */
                args: unknown;
                /** @description Provenance of the tool (builtin / mcp / plugin / skill). Omitted when absent. */
                source?: components["schemas"]["Source"];
                /** @description Optional human-facing display metadata. Omitted when absent. */
                display?: components["schemas"]["Display"];
            };
        } | {
            /** @constant */
            type: "tool_result";
            data: {
                /** @description Id matching the originating ToolUse.call_id. */
                call_id: string;
                /** @description Whether the tool succeeded. */
                ok: boolean;
                /** @description Result content blocks (multimodal-capable). Absent when the tool produced no output; present otherwise. Independent of `ok`. */
                content?: components["schemas"]["ContentBlock"][];
                /** @description Error message; present when not ok. */
                error_message?: string;
            };
        } | {
            /** @constant */
            type: "image";
            data: {
                /** @description Where the image bytes come from. */
                source: components["schemas"]["ImageSource"];
            };
        };
        /** @description Incremental delta carried by a content_block_delta stream event. Internally tagged by `type` (snake_case). The set of variants only grows; consumers MUST ignore unknown type values. */
        BlockDelta: {
            /** @constant */
            type: "text_delta";
            /** @description Text chunk appended to the current Text content block. */
            text: string;
        } | {
            /** @constant */
            type: "thinking_delta";
            /** @description Thinking chunk appended to the current Thinking content block. */
            thinking: string;
        } | {
            /** @constant */
            type: "input_json_delta";
            /** @description Partial JSON string to be concatenated into the final args object. */
            partial_json: string;
        } | {
            /** @constant */
            type: "signature_delta";
            /** @description Signature chunk. */
            signature: string;
        } | {
            /** @constant */
            type: "citations_delta";
            /** @description The citation being appended. */
            citation: components["schemas"]["Citation"];
        };
        /**
         * @description Role of the message author.
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /**
         * @description Reason the model stopped generating. Open set; consumers tolerate unknown values. end_turn: natural stopping point. max_tokens: context or output token limit hit. stop_sequence: configured stop sequence matched. awaiting_input: HITL pause (message_ask_user). cancelled: task was cancelled. failed: task failed with error.
         * @enum {string}
         */
        StopReason: "end_turn" | "max_tokens" | "stop_sequence" | "awaiting_input" | "cancelled" | "failed";
        /** @description Token accounting for a completed message. */
        Usage: {
            /**
             * Format: int64
             * @description Tokens consumed by the prompt/context.
             */
            input_tokens: number;
            /**
             * Format: int64
             * @description Tokens produced by the model.
             */
            output_tokens: number;
        };
        /**
         * @description Physical kind of an attachment.
         * @enum {string}
         */
        AttachmentKind: "file" | "image";
        /**
         * @description Where an attachment came from.
         * @enum {string}
         */
        AttachmentSource: "user_upload" | "agent_generated";
        /** @description A file or image attached to a message. */
        Attachment: {
            /** @description Opaque attachment identifier. */
            id: string;
            /** @description Human-facing file name. */
            name: string;
            /** @description MIME type, e.g. image/png. */
            mime_type: string;
            /**
             * Format: int64
             * @description File size in bytes.
             */
            size_bytes: number;
            /** @description Download or reference URI. */
            uri: string;
            /** @description Text extracted from the file, if available. Omitted when absent. */
            extracted_text?: string;
            kind: components["schemas"]["AttachmentKind"];
            source: components["schemas"]["AttachmentSource"];
        };
        /** @description Structured error attached to a failed message. */
        MessageError: {
            /** @description Machine-readable error code. */
            code: string;
            /** @description Human-readable description. */
            message: string;
        };
        /** @description The message envelope: the unit of history and the live-stream accumulation. Returned by GET /v1/tasks/{id}/history; also opened by message_start and finalized by message_stop on the live stream. */
        Message: {
            /** @description Opaque message identifier. */
            id: string;
            /** @description Id of the task this message belongs to. */
            task_id: string;
            /**
             * Format: int64
             * @description Monotonically increasing sequence number within the task.
             */
            seq: number;
            role: components["schemas"]["MessageRole"];
            /** @description Typed content blocks making up the message body. Omitted when empty (e.g. the shell opened by message_start). */
            content?: components["schemas"]["ContentBlock"][];
            /** @description Reason the model stopped, if the message is complete. Omitted while streaming. */
            stop_reason?: components["schemas"]["StopReason"];
            /** @description Token usage for this message, if available. Omitted when absent. */
            usage?: components["schemas"]["Usage"];
            /** @description Model identifier that generated this message. Omitted when absent. */
            model?: string;
            /** @description Files or images attached to this message. Omitted when empty. */
            attachments?: components["schemas"]["Attachment"][];
            /** @description Structured error, if the message represents a failure. Omitted when absent. */
            error?: components["schemas"]["MessageError"];
            /**
             * Format: date-time
             * @description ISO 8601 creation timestamp.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description ISO 8601 completion timestamp; absent while the message is streaming.
             */
            completed_at?: string;
        };
        /** @description A paginated slice of messages from a task's history. Items within a page are ordered ascending (oldest first, chronological). Pages walk newest -> older: pass next_before_seq as the `cursor` query parameter to fetch the next (older) page. Absent next_before_seq means the log is exhausted. */
        MessagePage: {
            /** @description Messages in this page, ascending by seq (oldest first). A whole turn is never split across pages, and no message is repeated or skipped between pages. */
            items: components["schemas"]["Message"][];
            /**
             * Format: int64
             * @description Cursor: pass as the `cursor` query parameter to fetch the previous (older) page. Absent on the last page.
             */
            next_before_seq?: number;
        };
        /** @description Block-oriented praxis stream event. Internally tagged by `type` (snake_case). Replaces the old RuntimeEvent. The cogito-to-praxis mapping lives in praxis-runtime. The set of variants only grows; consumers MUST ignore unknown type values. */
        StreamEvent: {
            /** @constant */
            type: "message_start";
            message: components["schemas"]["Message"];
        } | {
            /** @constant */
            type: "content_block_start";
            /** @description Zero-based index of this block within the message. */
            index: number;
            /** @description The block shell (no content yet). */
            content_block: components["schemas"]["ContentBlock"];
        } | {
            /** @constant */
            type: "content_block_delta";
            /** @description Zero-based index of the block being updated. */
            index: number;
            /** @description The delta to apply. */
            delta: components["schemas"]["BlockDelta"];
        } | {
            /** @constant */
            type: "content_block_stop";
            /** @description Zero-based index of the completed block. */
            index: number;
        } | {
            /** @constant */
            type: "message_delta";
            /** @description Reason the model stopped, if known at this point. Omitted when absent. */
            stop_reason?: components["schemas"]["StopReason"];
            /** @description Cumulative token usage for the message, if provided. Omitted when absent. */
            usage?: components["schemas"]["Usage"];
        } | {
            /** @constant */
            type: "message_stop";
        } | {
            /** @constant */
            type: "turn_paused";
        } | {
            /** @constant */
            type: "turn_resumed";
        } | {
            /** @constant */
            type: "skill_activation_requested";
            /** @description The name of the skill the model wants to activate. */
            skill_name: string;
        } | {
            /** @constant */
            type: "stream_end";
            task_status: components["schemas"]["TaskStatus"];
        } | {
            /** @constant */
            type: "ping";
        };
        /**
         * @description Lifecycle states for a praxis task.
         * @enum {string}
         */
        TaskStatus: "draft" | "running" | "paused" | "awaiting_input" | "completed" | "failed" | "cancelled";
        /** @description Summary of a task returned by create/get/list. */
        TaskSummary: {
            /** Format: uuid */
            id: string;
            title?: string | null;
            status: components["schemas"]["TaskStatus"];
            /** Format: uuid */
            project_id?: string | null;
        };
        /** @description A page of tasks. `next_cursor` is an opaque cursor for the next page; null/absent means no more pages. */
        TaskList: {
            items: components["schemas"]["TaskSummary"][];
            next_cursor?: string | null;
        };
        /** @description Uniform error response body. `code` is a stable, machine-dispatchable string (open set; consumers must tolerate unknown codes). `message` is human-readable and not stable. */
        ErrorBody: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description Inbound payload for creating a task. */
        CreateTaskRequest: {
            title?: string | null;
            strategy_ref?: string | null;
            user_input?: string | null;
            /** Format: uuid */
            project_id?: string | null;
        };
        /** @description Summary of a project returned by create/list. */
        ProjectSummary: {
            /** Format: uuid */
            id: string;
            title: string;
        };
        /** @description A page of projects. `next_cursor` is an opaque cursor for the next page; null/absent means no more pages. */
        ProjectList: {
            items: components["schemas"]["ProjectSummary"][];
            next_cursor?: string | null;
        };
        /** @description Inbound payload for creating a project. */
        CreateProjectRequest: {
            title: string;
        };
        /** @description Discovery descriptor for a registered resource. v0.2.0 emits only skills; plugin/mcp/connector are forward-shaped. See the resource-registry design doc. */
        ResourceDescriptor: {
            /** @description Stable identifier; the value clients pass as a skill hint. */
            id: string;
            /** @description One of: skill | plugin | mcp | connector. v0.2.0: always "skill". */
            kind: string;
            /** @description Human-facing label. v0.2.0: equals id. */
            display_name: string;
            /** @description One-line what/when. Load-bearing: also the model's routing signal. */
            description: string;
            /** @description Optional semver from SKILL.md frontmatter. */
            version?: string | null;
            icon?: string | null;
            /** @description Provenance: repo | user | plugin | system. */
            source?: string;
            /** @description Visibility: global | tenant | project. v0.2.0: always "global". */
            scope: string;
            /** @description Binding semantics: hint | enable | authorize. Skills are always "hint". */
            binding: string;
            /** @description Only meaningful for enable/authorize bindings; null for hint. */
            enabled?: boolean | null;
        };
        /** @description A page of skill descriptors. next_cursor null/absent means no more pages. */
        SkillList: {
            items: components["schemas"]["ResourceDescriptor"][];
            next_cursor?: string | null;
        };
        /** @description A skill descriptor plus its SKILL.md instructions body. */
        SkillDetail: {
            id: string;
            kind: string;
            display_name: string;
            description: string;
            version?: string | null;
            icon?: string | null;
            source?: string;
            scope: string;
            binding: string;
            enabled?: boolean | null;
            /** @description SKILL.md body, frontmatter stripped. */
            instructions?: string | null;
        };
        /** @description Body for starting a task's first turn. */
        StartTaskRequest: {
            user_input: string;
            /** @description Optional name of a registered skill to prefer for this task. A hint, not a lock: the model may still select a different skill. Unregistered hints are ignored. */
            skill_hint?: string;
            /** @description Optional list of registered skill names to prefer for this task. Hints, not locks: unregistered names are ignored. Unioned with skill_hint (which is retained for backward compatibility). */
            skill_hints?: string[];
        };
        /** @description Body for sending a follow-up user message into a running task. */
        SendMessageRequest: {
            text: string;
        };
        /** @description Body for answering a pending message_ask_user question. */
        AnswerRequest: {
            /** @description The `tool_use.call_id` of the pending `message_ask_user` block to answer. */
            ask_id: string;
            answer: string;
        };
    };
    responses: {
        /** @description Error response. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Retryable error. The Retry-After header advises a wait (seconds) before retrying. */
        RetryableError: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        /** @description Max items per page. Server returns a single page in v0.1.0; pagination logic is deferred. */
        Limit: number;
        /** @description Opaque pagination cursor from a prior response's next_cursor. Ignored until pagination ships. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is live. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTasks: {
        parameters: {
            query?: {
                /** @description Max items per page. Server returns a single page in v0.1.0; pagination logic is deferred. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a prior response's next_cursor. Ignored until pagination ships. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tasks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Max items per page. Server returns a single page in v0.1.0; pagination logic is deferred. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a prior response's next_cursor. Ignored until pagination ships. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listSkills: {
        parameters: {
            query?: {
                /** @description Max items per page. Server returns a single page in v0.1.0; pagination logic is deferred. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a prior response's next_cursor. Ignored until pagination ships. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of skill descriptors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillList"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The skill. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    startTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTaskRequest"];
            };
        };
        responses: {
            /** @description Accepted; task is starting. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["RetryableError"];
            503: components["responses"]["RetryableError"];
        };
    };
    sendTaskMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Accepted; the message was submitted to the session. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["RetryableError"];
        };
    };
    taskEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of StreamEvent frames. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["RetryableError"];
        };
    };
    taskHistory: {
        parameters: {
            query?: {
                /** @description Max items per page. Server returns a single page in v0.1.0; pagination logic is deferred. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a prior response's next_cursor. Ignored until pagination ships. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of Message objects, ascending (oldest first) within the page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    cancelTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task cancelled. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    completeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task completed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Answer accepted; turn resumes asynchronously. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
}
