// praxis wire types — re-exported from the generated OpenAPI client.
//
// As of praxis 0.1.5 BOTH event unions are defined in the OpenAPI document
// (components.schemas.RuntimeEvent / HistoryEvent), so they are generated by
// `openapi-typescript` (run `pnpm --filter @ash/web gen:praxis`) rather than
// hand-mirrored. praxis owns the contract; regenerate when it revises.
// (Supersedes the hand-authored RuntimeEvent union; see ADR-0015.)

import type { components } from "./generated";

export type TaskSummary = components["schemas"]["TaskSummary"];
export type CreateTaskRequest = components["schemas"]["CreateTaskRequest"];
export type PraxisTaskStatus = components["schemas"]["TaskStatus"];
export type AnswerRequest = components["schemas"]["AnswerRequest"];

/** SSE runtime event stream (delta-shaped tagged union, discriminator `type`). */
export type RuntimeEvent = components["schemas"]["RuntimeEvent"];

/** Historical conversation event (completed-block tagged union). */
export type HistoryEvent = components["schemas"]["HistoryEvent"];
export type HistoryItem = components["schemas"]["HistoryItem"];
export type TaskHistoryPage = components["schemas"]["TaskHistoryPage"];
